backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images"
collections:
- label: "Pages"
  name: "pages"
  files:
    - label: "Contact Page"
      name: "contact"
      file: "site/content/about/_index.md"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Seo Keywords, name: seo_keywords, widget: string}
        - {label: Seo Description, name: seo_description, widget: string}
        - {label: Google Map Coordinates, name: google_map_coordinates, widget: string}
        - {label: Featured Image, name: featured_image, widget: image}
